### ISSUE TITLE
[Win 10] Build failure compiling v2 branch (Rack-SDK-2)

### ISSUE THREAD

**Issue by SteveRussell33** [liquidcitymotors/Via-for-VCVRack#23]
```
Via/modules/sync3/sync3_modes.cpp: In member function 'void ViaSync3::handleButton2ModeChange(int32_t)':
Via/modules/sync3/sync3_modes.cpp:18:15: error: 'scales' was not declared in this scope
   18 |  numerators = scales[mode].numerators;
      |               ^~~~~~
make: *** [../../compile.mk:68: build/./Via/modules/sync3/sync3_modes.cpp.o] Error 1
```

**Comment by liquidcitymotors** [comment]
Thanks for the heads up about these bad commits, v1 and v2 should both build now. Please re-open if you run into any issues.
